### ISSUE TITLE
Version / Build number together with App version

### ISSUE THREAD

**Issue by Kaspik** [DataDog/dd-sdk-ios#1026]
Good afternoon!

Currently some fields are added automatically, like this `browser` / `agent` dictionary or `version` field.

Would it be possible to also add `versionNumber` (Let's say app is `9.50.0 (1475)` - so `1475`) or should we go our own way and add that field manually the same we added `thermalState` for example?

It's possible to have logs from multiple builds of the same version so this field would be super helpful.

<img width="578" alt="Screenshot 2022-10-19 at 14 40 44" src="https://user-images.githubusercontent.com/7204168/196694464-516a33b9-75f9-41ea-a115-fed99898fda0.png">
<img width="432" alt="Screenshot 2022-10-19 at 14 42 03" src="https://user-images.githubusercontent.com/7204168/196694474-65a621a7-9d8b-4e97-b19a-1bc377f92d3a.png">

**Comment by ncreated** [comment]
Hey @Kaspik 👋. Currently `version` is made by bundle version:
https://github.com/DataDog/dd-sdk-ios/blob/d2230acdc9ba9defded481f653c33f850bef9a95/Sources/Datadog/Datadog.swift#L29

which resolves to [`CFBundleShortVersionString`](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring) if available and fallback to [`CFBundleVersion`](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion) otherwise. It is not possible to customize it further at this moment with official APIs. However, I understand your use case and supporting custom `version` is something I will bring to our team table for discussion.

Meantime you can consider sending your own version (e.g. `ownVersion`) attribute and configuring it however you want. If you then [create a facet](https://docs.datadoghq.com/real_user_monitoring/explorer/search/#facets), this value will be queryable and searchable same way as default `version`.

There is yet no convenient way to set global attributes to the entire SDK (like `version` is done), but you could set it on logger and / or RUM monitor respectively. For that please have a look at this comment https://github.com/DataDog/dd-sdk-ios/issues/721#issuecomment-1070965831.

**Comment by Kaspik** [comment]
Hey @ncreated !

Thanks for pointing me to the code. Isn't that exactly the thing I'm asking for, where DataDog is using it incorrectly as a fallback?

![](https://i.stack.imgur.com/HNrrs.jpg)

The fallback value (in your case) is the Build number in case Version number is not available. So in case it would fail to get `9.50.0` it would send version `1475` which is incorrect - that's Build number.

**Comment by Kaspik** [comment]
Thanks for the discussion! Either configurable or having both by default sounds good to me.

>  For example "build string" seems more practical for troubleshooting (it identifies a certain version of the code), but "version number" might be more convenient for data analysis (no hassle with searching for the right build string).

And exactly for this ^^ I think having both would be more valuable option than settings. 🙂 Let me know what you decide with the team. 🙌🏼
