### ISSUE TITLE
Datadog preventing SwiftUI Preview from loading

### ISSUE THREAD

**Issue by TarekSalama** [DataDog/dd-sdk-ios#1040]
### The issue

Seems like there is a bug with Xcode 14 + some SPM libraries and for my project it's only Datadog that's causing this issue. So I get the error below every time I resume SwiftUI Previews however the project runs fine on the simulator. 
I tried re-adding Datadog as Dynamic and without specifying Dynamic nor Static (the first option that comes up when I add the Swift Package) but they all gave me the `missing required module 'datadog private'` error at the `import Datadog` line.

I am also a little bit confused because it shows that 1.12.1 is Datadog's version however it's defined as `1.5.2 - Next Major` in Xcode.

One last thing, Xcode 13 is not compatible with macOS Ventura so I am forced to use Xcode 14. It seems that one work around for now is to launch Xcode 13 from Xcode (in the Applications folder) -> Contents -> MacOS -> Xcode but it's very inconvenient and it could maybe break in the future.

This is a reference to the main issue: https://developer.apple.com/forums/thread/707569
```
HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x000060009e753120):'DatadogStatic'>)
```
---

#### Datadog SDK version:

1.12.1 + Xcode 14

#### Last working Datadog SDK version:

1.12.1 + Xcode 13

#### Dependency Manager:

SPM

#### Other toolset:

No

#### Xcode version:

Xcode 14.1

#### Swift version:

5.7.1

#### Deployment Target:

iOS 14.4

#### macOS version:

Ventura 13.0

**Comment by maxep** [comment]
Hey @TarekSalama 👋 

It looks similar to https://github.com/DataDog/dd-sdk-ios/issues/1027, can you try to link against `Datadog` library instead of `DatadogStatic`?

**Comment by TarekSalama** [comment]
I am on an M1 Mac if that helps. I tried opening Xcode 14 in Rosetta mode and natively with the `Datadog` library instead of `DatadogStatic` but that didn't help either.

**Comment by ncreated** [comment]
Hey @TarekSalama 👋. I'm trying to diagnose this problem, but everything works on my end. Could you help us on finding the minimal set list of steps to reproduce it?

I'm trying:
1. Create new iOS app (SwiftUI) project with Xcode 14.1
2. Add `dd-sdk-ios` dependency, version 1.12.1 (through SPM):

<img width="807" alt="Screenshot 2022-11-15 at 16 57 52" src="https://user-images.githubusercontent.com/2358722/201966218-f9d8fdbe-37d0-438a-881c-e94fdd41318e.png">

3. Add Datadog init snippet and force the SwiftUI preview to be build & rendered few times:

<img width="1552" alt="Screenshot 2022-11-15 at 16 55 02" src="https://user-images.githubusercontent.com/2358722/201966662-1aacc0a4-c0d4-4671-891a-aaa17909868f.png">

Everything works fine 🤔💭 (I'm on macOS Monterey 12.6.1 though).

Because I don't see much difference in my vanilla app setup and yours, could you please try to isolate the problem, so we can reproduce it on our side? That would also help eliminating external factors - like macOS version or some other setting in your project causing the issue.

---

Like @maxep mentioned, we already solved the issue with SwiftUI previews in #1027. The problem was our SDK enforcing either dynamic or static linking of the dependency. It was improved in #949, shipped in [1.12.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.12.0).

**Comment by TarekSalama** [comment]
> Hey @TarekSalama 👋. I'm trying to diagnose this problem, but everything works on my end. Could you help us on finding the minimal set list of steps to reproduce it?
> 
> I'm trying:
> 
> 1. Create new iOS app (SwiftUI) project with Xcode 14.1
> 2. Add `dd-sdk-ios` dependency, version 1.12.1 (through SPM):
> 
> <img alt="Screenshot 2022-11-15 at 16 57 52" width="807" src="https://user-images.githubusercontent.com/2358722/201966218-f9d8fdbe-37d0-438a-881c-e94fdd41318e.png">
> 
> 3. Add Datadog init snippet and force the SwiftUI preview to be build & rendered few times:
> 
> <img alt="Screenshot 2022-11-15 at 16 55 02" width="1552" src="https://user-images.githubusercontent.com/2358722/201966662-1aacc0a4-c0d4-4671-891a-aaa17909868f.png">
> 
> Everything works fine 🤔💭 (I'm on macOS Monterey 12.6.1 though).
> 
> Because I don't see much difference in my vanilla app setup and yours, could you please try to isolate the problem, so we can reproduce it on our side? That would also help eliminating external factors - like macOS version or some other setting in your project causing the issue.
> 
> Like @maxep mentioned, we already solved the issue with SwiftUI previews in #1027. The problem was our SDK enforcing either dynamic or static linking of the dependency. It was improved in #949, shipped in [1.12.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.12.0).

Hmm, I tried it in an empty new project and it seems to work fine. I even added all the other SPM dependencies and it's still working fine. 

It's worth noting though that I am installing the normal/default Datadog library rather than the static one so the issue I am getting is `missing required module 'datadog private'` when I try to compile on my real project. I tried compiling on my iPhone and on the simulator.

So given these findings; what else should I compare between the empty new project and the real one to further isolate the issue?

**Comment by ncreated** [comment]
@TarekSalama thank you a lot for confirmation - it then looks ok on our side 🤔💭. Though, the problem could come from migrating from Xcode 13.x to Xcode 14.x with `dd-sdk-ios` installed.

My advice would be to delete any SPM cache you have and to inspect `Package.resolved` (or even string search derived data for your project) to see if there are any uses of `DatadogDynamic` and `DatadogStatic` around. Since `1.12.x` we provide `Datadog` variant (with no enforcing "static" / "dynamic"), which should be preferred. Please share any findings 🙏.

**Comment by TarekSalama** [comment]
I cleared my derived folder and recloned the project from Github and now I notice that the error is complaining about Datadog working with my app's extension.
<img width="519" alt="Screenshot 2022-11-20 at 9 44 05 PM" src="https://user-images.githubusercontent.com/11663696/202922693-cc65de76-62dd-4870-99cc-78e124ca3899.png">
<img width="660" alt="Screenshot 2022-11-20 at 9 42 48 PM" src="https://user-images.githubusercontent.com/11663696/202922697-4daf5c08-9d82-4a07-a4e2-adbbc4ba7c13.png">

**Comment by TarekSalama** [comment]
I don't know if this is related in a way https://stackoverflow.com/questions/63503160/swiftui-previews-not-working-when-using-firebase-analytics-pod

**Comment by ncreated** [comment]
Hey @TarekSalama 👋 

> I cleared my derived folder and recloned the project from Github and now I notice that the error is complaining about Datadog working with my app's extension.

And did it work regarding the original issue with SwiftUI previews?

I tried linking `dd-sdk-ios` version `1.12.1` to iOS extension in the same SwiftUI app and once again, it worked without any problem. It builds correctly for regular app, for SwiftUI preview and for app extension:

<img width="398" alt="Screenshot 2022-11-29 at 11 04 10" src="https://user-images.githubusercontent.com/2358722/204500126-8fb47109-9726-4443-aa5d-0c05b9176c96.png">

It doesn't require any build customizations other than linking `Datadog` to an app and extension targets:

<img width="1080" alt="Screenshot 2022-11-29 at 11 04 30" src="https://user-images.githubusercontent.com/2358722/204500407-1f8566db-3e52-4d29-9b54-4510d61e07dd.png">

<img width="1070" alt="Screenshot 2022-11-29 at 11 04 42" src="https://user-images.githubusercontent.com/2358722/204500396-19c61c96-abec-4873-a588-f7e6f534a7df.png">

---

I tend to think that there must be some complexity or custom configuration in your project that is causing the problem. As it worked for you on fresh new project, I don't think this is `dd-sdk-ios` problem. To track it further, I'd recommend you trying to enrich the vanilla project with more and more flavours from your original app, until you find the one that's causing the problem.

> I don't know if this is related in a way https://stackoverflow.com/questions/63503160/swiftui-previews-not-working-when-using-firebase-analytics-pod

Hard to say - I'll rather bet on removing customization, than adding it 🙂, but it's impossible for me to guess, w/o knowing the complexity of your app project.

@TarekSalama please let us know if you made it work 🤞.

**Comment by TarekSalama** [comment]
Oh. It seems that when I reinstalled Datadog without being static, it wasn't added to my extension so that's why Xcode was complaining. But yea switching to the regular Datadog definitely fixed my first issue.
Thanks a lot!
