### ISSUE TITLE
Network traffic (= traces) not captured for `URLSession.data(...)` methods

### ISSUE THREAD

**Issue by gdeff** [DataDog/dd-sdk-ios#1288]
Hello,

In our iOS project we have set the Datadog SDK and activated trace collection.

The bug is that our requests/responses are not captured by Datadog. No trace is sent to Datadog server so we cannot find them into the Datadog UI.

After a little of investigation in the Datadog iOS SDK code, we noticed that there is a swizzling mechanism on `URLSession.dataTask()` methods. This mechanism is responsible for capturing traces.
In our project, we do not use `URLSession.dataTask()` methods but `URLSession.data()` methods which are their "async/await" version and available since iOS 15. More precisely, we observe that the following methods are not supported by this swizzling mechanism:

- `URLSession.data(for: URLRequest) -> (Data, URLResponse)`
- `URLSession.data(from: URL) -> (Data, URLResponse)`
- `URLSession.data(for: URLRequest, delegate: (URLSessionTaskDelegate)?) -> (Data, URLResponse)`
- `URLSession.data(from: URL, delegate: (URLSessionTaskDelegate)?) -> (Data, URLResponse)`

Could you, please, update the code in order that the Datadog iOS SDK support these methods ?

**Comment by ganeshnj** [comment]
Since iOS 16, there have been some changes for async APIs in `URLSession` where not all delegates methods are called. This causes in failure in detection of request start and stop.

Only `NSURLSessionTask.resume` and `URLSessionTaskDelegate.urlSession(_:task:didFinishCollecting:)` are called, hence we need to modify the way we collect the metrics for async APIs (atleast) for iOS 16 and above.

I quickly checked the hypothesis on https://github.com/DataDog/dd-sdk-ios/compare/develop...ganeshnj/fix/1288-url-session-instrumentation branch and I was able to collect metrics for async APIs.

There was a similar issue in https://github.com/open-telemetry/opentelemetry-swift/pull/398 as well which was recently fixed.

**Comment by ncreated** [comment]
Instrumentation for async/await APIs was introduced in [**2.5.0**](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.5.0) - I'm closing this issue.
