### ISSUE TITLE
Unexpected long duration for tracing operation

### ISSUE THREAD

**Issue by joseewu** [DataDog/dd-sdk-ios#1450]
### The thing

Hi Datadog team, hope you are all doing good. 

I am recently trying to investigate some weird trace duration we observed.

Like the screenshot below, we are tracing time duration for app start up time. 
We call startSpan when `didFinishLaunchingWithOptions` gets called in `AppDelegate` (after configure Datadog SDK) and we have some api calls to set up the app. 

After those calls, we open the home page and then we call finish span. 

So it's like

app launch -> **start span** -> few calls (which take time) -> call ends -> **finish span** -> show home screen

![Screenshot 2023-09-01 at 11 27 27](https://github.com/DataDog/dd-sdk-ios/assets/8402073/30321d14-f7e3-416c-ae86-e763bb1c1305)

Ideally those api calls take few second or 1 mins, but we observe some of the traces take 1d or even 1 mon. 

We are thinking if we did something wrong on our side. (for example, not calling finish properly or not active the span etc)

Do you know what could lead to this issue?

**Comment by ganeshnj** [comment]
hi @joseewu and thanks for opening the issue.

We have seen similar issue with longer startup being measure and it was due to the [prewarming](https://developer.apple.com/documentation/uikit/app_and_environment/responding_to_the_launch_of_your_app/about_the_app_launch_sequence) feature introduced in iOS 15. 

Although, the documentation doesn't say that  `didFinishLaunchingWithOptions` is called during the prewarming which can happen hours, days or weeks before application is actually launched but the observations tell different story. Check [github discussion](https://github.com/MobileNativeFoundation/discussions/discussions/146) and [twitter thread](https://twitter.com/FelixOmni/status/1466140731324739592).

One quick way to confirm your app behavior is by checking if this happens on < iOS 15 or not because prewarming only works iOS 15 or later.

**Comment by joseewu** [comment]
Hi @ganeshnj thanks for the quick response! we currently don't log the os information on tracer, will add it and confirm to you!

**Comment by joseewu** [comment]
hi @ganeshnj we got some data back by adding OS version in the APM trace. 

It looks like it also happens on ios 14 not only ios 15 above. 

![Screenshot 2023-09-10 at 17 03 22](https://github.com/DataDog/dd-sdk-ios/assets/8402073/e9716484-964e-44c4-98df-94577cd9333b)

Maybe it's not really prewarming, it's because I call the Span to close to the start up cycle? In app delegate 's didFinishLaunchingWithOptions. 

Do you have recommended approach to measure the start-up time?

Thanks so much!

**Comment by joseewu** [comment]
@ganeshnj kindly ask if you can provide information on your side? 
Can you confirm it's [prewarming](https://developer.apple.com/documentation/uikit/app_and_environment/responding_to_the_launch_of_your_app/about_the_app_launch_sequence) feature? Since we still got long duration tracer from ios 14 🙏

**Comment by ganeshnj** [comment]
Thanks for screenshot @joseewu 

On iOS 14, it looks unrelated to prewarming. I'm afraid to recommend anything other than official. You may want to look at https://developer.apple.com/documentation/metrickit. We struggle to define the app launch as well.

I have not tried but you may want to look at https://www.avanderlee.com/swift/metrickit-launch-time/

**Comment by joseewu** [comment]
yes 👍 thanks for the help!
got it, I was thinking of using metrickit as well. close the issue.
