### ISSUE TITLE
Build error -No such module 'Datadog'- after updating to Cocoapods 1.13

### ISSUE THREAD

**Issue by tobiaslewinzon** [DataDog/dd-sdk-ios#1492]
### The issue

- Last week we were experiencing this error when building Xcode 15 on older iOS than 17.0.
`Error: DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead `

- We were waiting for Cocoapods newest release that would fix this. Cocoapods 1.13 is out to address this: https://github.com/CocoaPods/CocoaPods/releases/tag/1.13.0
- After updating, we are now stuck at `No such module 'Datadog'`
- Note: This is the same error we got when trying some of the Podfile script fixes prior to the Cocoapods 1.13 release: https://github.com/CocoaPods/CocoaPods/issues/12065

---

#### Datadog SDK version:

2.2.1

#### Last working Datadog SDK version:

2.2.1, or any version if I run on Xcode < 15 or Xcode 15 in iOS 17.0 and above.

#### Dependency Manager:

Cocoapods.

#### Xcode version:

Version 15.0 (15A240d)

#### Swift version:

Whatever Xcode 15 runs with.

#### Deployment Target:

iOS 16.0 and above.

#### macOS version:

Ventura 13.5.1 (22G90)

**Comment by maciejburda** [comment]
Hey!

Thanks for raising the issue.
I spotted a typo and just wanted to make sure if it's just a typo in the description or actually in the import statement.

Error message says: `No such module 'Datagog'`, but it should be `Datadog` of course.

**Comment by tobiaslewinzon** [comment]
Hello! Thanks for the immediateness. Typo fixed.

**Comment by fuadwaheed** [comment]
Facing same issue, need urgent help.

**Comment by maxep** [comment]
Hey!
The `2.2.1` does not include the `Datadog` module anymore. Since `2.0` we have split the SDK into modules, you can follow our [Migration Guide](https://github.com/DataDog/dd-sdk-ios/blob/develop/MIGRATION.md) to adopt this new major version. Otherwise, you can specify `'~> 1.23.0'` in your Podfile. 
Hope this helps!

**Comment by tobiaslewinzon** [comment]
Hey! I rolled back to `'~> 1.23.0'`, and now we are stuck at this crash when building into a physical device with iOS lower than 17.0. 

This is the crash that lead to us trying the SDK update, which lead to `Error: DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead`, which lead us to the Cocoapods update, which lead to opening this issue. Always when using Xcode 15 for iOS < 17.0.

![Screenshot 2023-09-26 at 09 19 37](https://github.com/DataDog/dd-sdk-ios/assets/50757181/9ce1e3eb-aff8-4bae-b948-68ab1485d7a8)

Thanks in advance!

**Comment by maxep** [comment]
Hi @tobiaslewinzon 👋 

Thanks for the report, the issue appears with Xcode 15 because we support down to iOS 11. We will address this on our side!
As a workaround, you can bump de minimum deployments version in the `Pods` target to iOS 12:

![image](https://github.com/DataDog/dd-sdk-ios/assets/6815992/13539fc0-0d47-4c76-a5a0-a31d72d63624)
