### ISSUE TITLE
Do we have a capability for sampling rate each span?

### ISSUE THREAD

**Issue by muukii** [DataDog/dd-sdk-ios#1534]
As we know, to measure the duration of something, we use Tracer which will be initialized from `Trace.enable` that takes a parameter for sampling rate.
So what if we want some specific span to measure in different sampling rate, how can we do this?

**Comment by maciejburda** [comment]
Thanks for reaching out @muukii!

Normally you should be able to achieve this by setting sampling rate to 100 and using custom `eventMapper` which is a part of the configuration. Although unfortunately I just checked and currently it is not supported. In the current implementation we don't allow dropping events or modifying their sample rate.

It seems like an easy change though. I'll discuss with the team and let you know.

**Comment by maciejburda** [comment]
Hello again @muukii 

I just discussed with the team, as long as the code change is fairly simple, the potential product repercussions might be more complex. For example when we drop a middle `Span` it will remove correlation in the flame graph between it's parent and it's child.

Would you be able to provide a bit more context on the exact use case you're trying to achieve?

**Comment by maciejburda** [comment]
Thanks for following up!

Alright, that's a completely valid scenario. I'll talk to product and see if it's something that we have already considered on the feature level.

On the technicalities - unfortunately Tracer does not provide standard initialisation, because it needs to be tied to a specific core. It is possible to spawn multiple cores with the same configuration and enable separate shared tracers in them with different sampling rate:
```swift
/// Enables Datadog Trace feature.
///
/// After Trace is enabled, use `Tracer.shared(in:)` to collect spans.
///
/// - Parameters:
///   - configuration: Configuration of the feature.
///   - core: The instance of Datadog SDK to enable Trace in (global instance by default).
public static func enable(
    with configuration: Trace.Configuration = .init(), in core: DatadogCoreProtocol = CoreRegistry.default
)
```

So it would be possible to do something like:
```swift
let core1 = Datadog.initialize(
    with: .init(
        clientToken: appConfig.clientToken, 
        env: appConfig.env
    ),
    trackingConsent: .granted
)

let core2 = Datadog.initialize(
    with: .init(
        clientToken: appConfig.clientToken,
        env: appConfig.env
    ),
    trackingConsent: .granted
)

Trace.enable(with: .init(sampleRate: 10), in: core1)
Trace.enable(with: .init(sampleRate: 50), in: core2)

let tracerWith10Sampling = Tracer.shared(in: core1)
let tracerWith50Sampling = Tracer.shared(in: core2)
```

Although it's not recommended approach as it produces unnecessary overhead of having two instances simultaneously.
Note that it will still cause the same problem mentioned in my previous post.

I'll get back to you when we have more clarity on the product level.

**Comment by muukii** [comment]
I appreciate your response.
I see, that is kind of technically possible but not recommended. I get it
