### ISSUE TITLE
Support for using `OSLog`

### ISSUE THREAD

**Issue by cheif** [DataDog/dd-sdk-ios#1553]
## The problem
We're currently using DataDog for our log collection, and currently we've got a custom logger that makes sure that we can send log-events of to different places (Datadog, console, file etc.). 
We would however like to start using [`OSLog`](https://developer.apple.com/documentation/os/oslog), which seems to becoming the defacto standard for logging on iOS. That would allow us to just do something like this when logging:
```swift
import OSLog

let logger = Logger(subsystem: Bundle.main.bundleIdentifier!, category: "Notifications")

logger.debug("Hello, this is \(name)")
```
And our code wouldn't need to deal with any custom loggers, etc.

There's support for attaching as a "sink" to these logs through [`OSLogStore`](https://developer.apple.com/documentation/oslog/oslogstore), a more through example [here](https://swiftwithmajid.com/2022/04/19/exporting-data-from-unified-logging-system-in-swift/). 

The problem we're coming up against is that there's currently no way to batch-send events to DataDog through the SDK, thus we can't really get the logs to DataDog right now.

### Support attaching to `OSLogStore` directly
A very nice solution from a end-user perspective would be to just be able to attach a `Datadog.Logger` to `OSLogStore` automatically, making this a single-line integration for the caller, exposing something like:
```swift
Datadog.initialize(...)
let ddLogger = Logger.builder.build()
try OSLogStore(scope: .currentProcessIdentifier).attach(ddLogger)
```

### Support for batch-sending events
This would mean some more work for the caller, but be more flexible. In this scenario the user would have to deal with getting the events from `OSLogStore` themselves, and then datadog would just support batch-sending events:
```swift
Datadog.initialize(...)
let ddLogger = Logger.builder.build()

let store = try OSLogStore(scope: .currentProcessIdentifier)
let position = self.positionForLastProcessedLog
let logs = try store.getEntries(at: position).compactMap { convertToDataDogEvent($0) }
await ddLogger.sendBatch(logs)
```

## Where to go from here
I'm curious if you think this would be a reasonable addition to the library? Is there some way of achieving this already? Do you think there are better alternatives to solve this problem?

**Comment by maciejburda** [comment]
Hey @cheif !

Thanks for opening the issue and providing so much details and a solution suggestion! 💪 

I'll bring the issue to the team to discuss and get back to you 🙌

**Comment by james-ff** [comment]
+1

**Comment by maciejburda** [comment]
Hello,

We carefully explored the request and unfortunately we cannot provide out of the box solution just yet.

We looked at the problem from different angles and we discovered a few things:
- Swizzling of logging functions is not possible because [Logger](https://developer.apple.com/documentation/os/logger) is not leveraging obj-c runtime.
- OSLogStore [getEntries](https://developer.apple.com/documentation/oslog/oslogstore/3204125-getentries), is only supported from iOS15+, and it returns list of [OSLogEntry](https://developer.apple.com/documentation/oslog/oslogentry) objects that are persisted by the system using rules defined in the [StoreCategory](https://developer.apple.com/documentation/oslog/oslogentry/storecategory). As of now we don't have a way in the SDK to remember which logs were already uploaded, which creates a risk of uploading the same logs multiple times. Although this is something that we're exploring, so there's a chance we'll add support for it in the future.

For the time being we can suggest a potential solution to a problem which would involve writing wrapper for loggers used in the system. Rough implementation of this could look like this:

```swift
import OSLog
import DatadogLogs

@available(iOS 14.0, *)
class LoggerWrapper {
    let datadogLogger = DatadogLogs.Logger.create()
    let osLog = Logger()

    public func log(level: OSLogType, message: String) {
        datadogLogger.log(
            level: level.asDatadogLogLevel(),
            message: "\(message)",
            error: nil,
            attributes: nil
        )
        osLog.log(level: level, "\(message)")
    }
}

extension OSLogType {
    func asDatadogLogLevel() -> LogLevel {
        switch self {
        case .debug:
            return .debug
        case .info:
            return .info
        case .error:
            return .error
        case .fault:
            return .critical
        default:
            return .info
        }
    }
}
```

Additionally, we're exploring integrating OSLog into our SDKs' internal loggers, but this requires a detailed analysis of privacy and utility considerations.

**Comment by cheif** [comment]
Thanks for taking this into consideration, and giving a very clear and well motivated answer. It sounds like this is something that might be possible in the future, which I'm happily waiting for.

Re: the wrapper solution, we're using something similar today (and I think a lot of people are), I think the main drawback to that is that it requires you to have a shared wrapper across all modules/packages, whereas just utilising `OSLog` directly would have the benefit that being the only dependency. Then where logs are stored could be decided at a higher level, e.g. in the `AppDelegate`. 
But I understand such a solution isn't possible right now, and that's totally fine.

**Comment by nickkaczmarek** [comment]
Following up here in mid 2026 to see if anything has changed since the last time this was looked into.
