### ISSUE TITLE
Extract OpenTracing dependencies from dd-sdk-ios and use as a dependency

### ISSUE THREAD

**Issue by joshskeen** [DataDog/dd-sdk-ios#1580]
### The thing

Including the opentracing dependencies as a copy inside of the dd-sdk-ios library breaks decoupling of components that will share tracing capabilities with other modules. 

Tell us the thing 🙂

Instead, those modules that require just opentracing behavior now require us to import the entirety of the datadog sdk to use the tracing interfaces. 

The android datadog sdk on the other hand [decouples these dependencies](https://github.com/DataDog/dd-sdk-android/blob/bece8a1f465b790a584d04e774768139acb28524/features/dd-sdk-android-trace/build.gradle.kts#L63C16-L63C16), making it much easier to provide an opentracing interface to consumers of trace behavior. 

iOS should bring their sdk in line with this design.

**Comment by ncreated** [comment]
@joshskeen The OT (OpenTracing) interface implemented by Datadog iOS Tracer is indeed a copy of [opentracing-swift](https://github.com/opentracing/opentracing-swift) interface. We made efforts to use it as an external dependency (see https://github.com/opentracing/opentracing-swift/pull/11), so our users could instrument their code against OT and avoid vendor locking. Due to no response, we decided to provide "conventional conformance" instead and copy the OT APIs to our project.

Speaking of today, where OT is officially deprecated and [OpenTelemetry](https://opentelemetry.io/) (OTel) is considered the new standard, we work on changing our iOS Tracer to be OTel-compatible. This may include extracting tracer interface or consuming it from official dependency (see [opentelemetry-swift](https://github.com/open-telemetry/opentelemetry-swift)). If you are in favour of externalizing `opentelemetry-swift` interfaces, you can check the proposal we opened in https://github.com/open-telemetry/opentelemetry-swift/issues/486.

Let us know if this makes sense to you 🙂.

**Comment by ncreated** [comment]
@joshskeen 👋 We finally achieved the API split in [**2.14.0**](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.14.0) 🎉. Like I said earlier, we implement Open Telemetry API, not Open Tracing as the latter is a deprecated standard. With 2.14.0 it is possible to instrument the code using OTel API and use Datadog iOS Tracer as implementation detail to avoid vendor-locking.

Because 2.14.0 achieves the split in subject and because no further work is planned for Open Tracing conformance on our side I'm closing this issue.
