### ISSUE TITLE
Expose all the properties in PerformancePresetOverride DataDogFeature

### ISSUE THREAD

**Issue by samueleperricone** [DataDog/dd-sdk-ios#1589]
### Improve PerfomancePresetOverride

The internal protocol `StoragePerformancePreset` exposes some threshold for the max size on disk used by SDK and the maximum time after the logs will be deleted, but this threshold values are hardcoded in an `internal` struct and the PerfomancePresetOverride
 protocol does not allow to provide override values. This is not optimal in case you want reliable logs and not to lose any log.

<img width="532" alt="Screenshot 2023-12-14 at 14 52 30" src="https://github.com/DataDog/dd-sdk-ios/assets/37908960/521f72e6-2557-43fd-8f5d-f2397465df14">

https://github.com/DataDog/dd-sdk-ios/blob/a53e62ed1f39cf3b525eeac607d6805a24513c09/DatadogCore/Sources/PerformancePreset.swift#L126

The ideal would be to extend the existing `PerfomancePresetOverride` allowing to customise all the properties including:

- maxDirectorySize
- maxFileAgeForRead

```
internal protocol StoragePerformancePreset {
    /// Maximum size of a single file (in bytes).
    /// Each feature (logging, tracing, ...) serializes its objects data to that file for later upload.
    /// If last written file is too big to append next data, new file is created.
    var maxFileSize: UInt64 { get }
    /// Maximum size of data directory (in bytes).
    /// Each feature uses separate directory.
    /// If this size is exceeded, the oldest files are deleted until this limit is met again.
    var maxDirectorySize: UInt64 { get }
    /// Maximum age qualifying given file for reuse (in seconds).
    /// If recently used file is younger than this, it is reused - otherwise: new file is created.
    var maxFileAgeForWrite: TimeInterval { get }
    /// Minimum age qualifying given file for upload (in seconds).
    /// If the file is older than this, it is uploaded (and then deleted if upload succeeded).
    /// It has an arbitrary offset  (~0.5s) over `maxFileAgeForWrite` to ensure that no upload can start for the file being currently written.
    var minFileAgeForRead: TimeInterval { get }
    /// Maximum age qualifying given file for upload (in seconds).
    /// Files older than this are considered obsolete and get deleted without uploading.
    var maxFileAgeForRead: TimeInterval { get }
    /// Maximum number of serialized objects written to a single file.
    /// If number of objects in recently used file reaches this limit, new file is created for new data.
    var maxObjectsInFile: Int { get }
    /// Maximum size of serialized object data (in bytes).
    /// If serialized object data exceeds this limit, it is skipped (not written to file and not uploaded).
    var maxObjectSize: UInt64 { get }
}
```

### Affected Version
Datadog SDK for iOS v2.5.0

**Comment by ncreated** [comment]
Hello @samueleperricone indeed the [`StoragePerformancePreset`](https://github.com/DataDog/dd-sdk-ios/blob/a53e62ed1f39cf3b525eeac607d6805a24513c09/DatadogCore/Sources/PerformancePreset.swift#L10C19-L10C43) and [`PerformancePresetOverride`](https://github.com/DataDog/dd-sdk-ios/blob/a53e62ed1f39cf3b525eeac607d6805a24513c09/DatadogInternal/Sources/Storage/PerformancePresetOverride.swift#L12) protocols are responsible for determining limits and timings in SDK core that impact batching and upload system. These values are managed internally and differ between products (Logs, Trace, RUM, Session Replay). The way we manage these values internally is however quite complex. It depends on anticipated usage of each product, the average size of its events, expected frequency of events and required rate for sending network requests to achieve reliable data transmission.

That said, we are skeptical about exposing these interfaces in public configuration, because SDK users do not have enough detail on each product requirements. Accepting arbitrary configurations will lead to misconfiguration problems and some SDK instances will no longer work efficiently, causing delays in digesting and uploading all data on time.

Instead, the SDK offers 3 different APIs for configuring its performance using following options:
- [batchSize](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios/?tab=swift#initialization-parameters): `.small`, `.medium`, `.large`
- [uploadFrequency](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios/?tab=swift#initialization-parameters): `.rare`, `.average`, `.frequent`
- `batchProcessingLevel` - added recently in [#1531](https://github.com/DataDog/dd-sdk-ios/pull/1531) to configure how many network requests the SDK can perform in each upload.

@samueleperricone it might be best to know what problem you try to solve exactly and if above options will work for you 🙂.

Because this issue is about exposing these interfaces, I'm going to close it as this isn't something we consider in our backlog. Feel free to provide more context.
