### ISSUE TITLE
[Missing Properties] Privacy Manifest, unable to generate privacy report

### ISSUE THREAD

**Issue by RoblesJ** [DataDog/dd-sdk-ios#1655]
### Privacy Report missing properties

We are working on setting up our modules privacy manifests (reference on issue: https://github.com/DataDog/dd-sdk-ios/issues/1406), when we attempted to use your privacy manifest introduced on v 2.7.0 we found it is missing the type of data it should declare for the usage of UserDefaults

<img width="908" alt="Screenshot 2024-02-05 at 15 52 10" src="https://github.com/DataDog/dd-sdk-ios/assets/86575603/7ca24adf-e7ef-45f9-979f-647b3601abd6">

I'll provide an example of a working manifest for reference.
<img width="797" alt="image" src="https://github.com/DataDog/dd-sdk-ios/assets/86575603/11db66e9-e165-424e-8fe0-6cd4fc20bbb1">

My conclusion would be that while you are manifesting you use user defaults you are not defining the reason of doing so.
Here is an example with a working manifest i attempted on a fork
<img width="1458" alt="Screenshot 2024-02-05 at 15 57 18" src="https://github.com/DataDog/dd-sdk-ios/assets/86575603/fb2af47f-5a1c-47f0-8dc8-2fef8fbef7e1">

**Comment by maxep** [comment]
Hey @RoblesJ 👋  Thank you for the report.

Indeed, our privacy manifest do not declare `NSPrivacyCollectedDataTypes` because those strongly depend on your configuration and usage. It appears that missing this key will prevent for generating the Privacy Report from the app archive.
Adding an empty array seems to fix the issue:
```xml
<key>NSPrivacyCollectedDataTypes</key>
<array></array>
```
