### ISSUE TITLE
Background sessions are reported at SwiftUI project

### ISSUE THREAD

**Issue by vani2** [DataDog/dd-sdk-ios#1673]
### Describe the bug

After I upgraded the project from React Native to SwiftUI project, the number of sessions increased around 4 times. I suspect this is because background sessions are considered foreground ones in SwiftUI. Or because the native app tracks sessions differently from cross-platform. 
My app has Bluetooth capability that works in the background, so that's why I suspect it wakes the app in the background several times per day and reports different sessions to RUM.

### Reproduction

Configure RUM 
```swift
let rumConfiguration = RUM.Configuration(
    applicationID: <app_id>,
    urlSessionTracking: RUM.Configuration.URLSessionTracking(),
    trackFrustrations: false,
    trackBackgroundEvents: false
)
RUM.enable(with: rumConfiguration)
```

<img width="1004" alt="Screenshot 2024-02-12 at 14 57 30" src="https://github.com/DataDog/dd-sdk-ios/assets/4734983/8188866e-d1ca-4424-b620-a5fe242b4833">

### Expected behavior

Background sessions are not reported.

#### Datadog SDK version:

2.7.0

#### Dependency Manager:

SPM

#### Xcode version:

`Xcode 15.2`

#### Deployment Target:

`iOS 15`

#### macOS version:

`macOS 14.3`

**Comment by ncreated** [comment]
Hey @vani2 👋. Please tell us more about the way your app is instrumented. Especially:
- which DD SDK APIs do you use for views tracking?
- do you start views manually using `RUMMonitor.shared().startView(...)` or rather use [our SwiftUI modifier](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/setup/swiftui/#instrument-views)?
- what is the earliest moment of invoking DD SDK code in your app?
- is your app 100% SwiftUI or is it hybrid scenario of mixing SwiftUI with UIKit or with React Native?

---
On background sessions tracking, please note that [`trackBackgroundEvents`](https://github.com/DataDog/dd-sdk-ios/blob/6bdaf452c03d52c703fb18745fe5ae3eb6b0e0e0/DatadogRUM/Sources/RUMConfiguration.swift#L104-L111) option determines if RUM events should be tracked when no active RUM view exists. It shouldn't be interpreted as tracking any events while app is in background.

https://github.com/DataDog/dd-sdk-ios/blob/6bdaf452c03d52c703fb18745fe5ae3eb6b0e0e0/DatadogRUM/Sources/RUMConfiguration.swift#L104-L111

If a view is started manually (`RUMMonitor.shared().startView(name: "MyView")`), it will be tracked no matter of `trackBackgroundEvents` and no matter if the app is currently in foreground or background or in the middle of transition.

**Comment by vani2** [comment]
Hi @ncreated , 

I use the SwiftUI modifier only for view-tracking.
Once my app starts, it initializes the Data Dog (the app delegate did finish launching).

My current app is SwiftUI 99%; the previous one was 100% on React Native, so the new one replaced the old one but uses the same app ID. Both apps work in the background with Bluetooth accessories, so is each background launch tracked no matter if `trackBackgroundEvents` is false?
If I remove using the modifier for view tracking, can it reduce the number of sessions?

**Comment by ncreated** [comment]
@vani2 I did some confidence check on our side, using SwiftUI application instrumented with `DatadogRUM` as in following code snippet. In the app I used location manager to track GPS location changes in background and send them as RUM actions.

The behaviour I observe is correct - even though the app is woken up for each location update, `trackBackgroundEvents` decides appropriately if a session should be created or not. The `.trackRUMView(name:)` is not causing views to be started in background (as SwiftUI doesn't fire underlying [`onAppear`](https://github.com/DataDog/dd-sdk-ios/blob/c067a71de94f5c910dd9d079e7baa00bb1551d25/DatadogRUM/Sources/Instrumentation/Views/SwiftUI/SwiftUIViewModifier.swift#L32) if the app is not in foreground).
```swift
@main
struct GH1673_bg_sessionsApp: App {
    init() {
        // Init Datadog SDK core
        // Enable RUM with: config.trackBackgroundEvents = false
    }

    var body: some Scene {
        WindowGroup { ContentView() }
    }
}

struct ContentView: View {
    @State private var selectedScreen: Int?
    var body: some View {
        NavigationStack {
            List {
                NavigationLink(value: 1) { Text("One") }
                NavigationLink(value: 2) { Text("Two") }
                NavigationLink(value: 3) { Text("Three") }
                Spacer()
            }
            .trackRUMView(name: "Menu") // Datadog instrumentation for SwiftUI views
            .navigationDestination(for: Int.self) { idx in
                ScreenView(screenNumber: idx)
                    .trackRUMView(name: "Screen \(idx)") // Datadog instrumentation for SwiftUI views
            }
        }
    }
}
```

> Both apps work in the background with Bluetooth accessories, so is each background launch tracked no matter if trackBackgroundEvents is false?

SDK doesn't track app launches, it tracks views that appear. It means that when using `.trackRUMView(name:)` modifier a view will be started each time when SwiftUI's `onAppear` is called. Because this doesn't happen when the app is woken up in background, the SDK will track no views in such case → so no sessions in the background.

The `trackBackgroundEvents` option in turn, decides on how to handle other events (like RUM actions, errors or resources) that happen while there is no view started. If enabled, when no view is started the SDK will start one for you, named `"Background"` to track the event. This is exactly what I verified in my confidence check: that RUM actions sent while app is in background with `trackBackgroundEvents: false` are ignored.

> If I remove using the modifier for view tracking, can it reduce the number of sessions?

Yes, but you won't be recording any RUM sessions this way. RUM sessions require views to be tracked.

--- 

@vani2 What you may want to verify in your app is that no `onAppear` is called when the app is woken up in background. Our SwiftUI instrumentation highly depends on the app respecting the default SwiftUI views lifecycle.

**Comment by vani2** [comment]
It looks like you're right, @ncreated. I've checked, and my session didn't appear if I do Bluetooth logic in the background. 

My only theory is that my native app is killed between user launches in a 4-hour window, so the framework treats it as different sessions, as React Native SDK treats it as one session.

**Comment by vani2** [comment]
@ncreated, please let me know if you have any other ideas about why the number of sessions has increased without an increase in user count. Otherwise, I'll close the issue.

**Comment by maciejburda** [comment]
Hey @vani2 

We briefly discussed your matter with the team and haven't came up with more ideas. We think that at this point it would be the best if you could reach out through [the official support channel](https://help.datadoghq.com/hc/en-us/requests/new), so we can investigate with access to the real data.
