### ISSUE TITLE
Crash on widget extension

### ISSUE THREAD

**Issue by ivopintodasilva** [DataDog/dd-sdk-ios#1690]
### The crash

This potential crash causes widgets to be inactive (and some times totally blank).
The only common clue in the stacktrace is Datadog's `DataUploadWorker` reading files from the disk:

<img width="836" alt="image" src="https://github.com/DataDog/dd-sdk-ios/assets/4477378/d9b45966-7116-47d9-8733-358ee1729ecc">

---

<img width="813" alt="image" src="https://github.com/DataDog/dd-sdk-ios/assets/4477378/9efa6816-439e-4706-8049-ccdc34614696">

---

<img width="846" alt="image" src="https://github.com/DataDog/dd-sdk-ios/assets/4477378/34ffe065-4270-490e-ac81-b5770d1a6da4">
<img width="846" alt="image" src="https://github.com/DataDog/dd-sdk-ios/assets/4477378/3a4d53cd-38fe-4354-8f56-02943f8143c5">

---

In order to avoid uploading logs from the widget extension, I tried to disable the upload altogether (and only write them to disk so that they are uploaded from the main app) but afaik it's not possible to achieve this in the current SDK.

Any suggestions on what I could try next?

### Reproduction

This crash is very difficult to replicate and I can't provide a project that does it consistently.
One pattern that I've detected is that it happens more frequently once the app is updated to a new version (eg. whenever we release an update to the app store).

---

#### Datadog SDK versions:

1.22.0

#### OS version:

<img width="246" alt="image" src="https://github.com/DataDog/dd-sdk-ios/assets/4477378/092a4ac7-ab9f-4206-a561-8bf838639906">

#### Deployment Target:

iOS 15

#### Environment:

Seems to happen more frequently once the app is updated to a new version (eg. whenever we release an update to the app store).

**Comment by maciejburda** [comment]
Thanks for reporting!

We'll look into it and let you know.

**Comment by maciejburda** [comment]
@ivopintodasilva I am trying to recreate the issue locally. Can you give me a hint about the exact type of widget you are using? Also, where in it's lifecycle are you using logger?

**Comment by ivopintodasilva** [comment]
thank you for looking into it! 🙏 

> Can you give me a hint about the exact type of widget you are using?

our widget extension has 4 different widgets:

- 3 "regular" widgets (using `StaticConfiguration` as the `WidgetConfiguration`)
- 1 configurable and interactive widget (using `AppIntentConfiguration` as the `WidgetConfiguration`). this is a todos widget that allows:
  - long-pressing to choose todo list to display in the widget
  - marking todos as done from the widget

> Also, where in it's lifecycle are you creating logs?

we are mostly creating logs once the timelines for widgets are created or on errors (network requests...)

**Comment by maciejburda** [comment]
Thanks for additional context.

Do you know what's the average volume of these logs for a single widget? 🤔

**Comment by ivopintodasilva** [comment]
Each widget can produce between 1 to ~20 logs and they can refresh their timelines every 15 minutes

**Comment by maciejburda** [comment]
@ivopintodasilva Do have the exception type and message?

**Comment by ivopintodasilva** [comment]
Here's the full crash report/stacktrace:

[2024-02-14_14-32-50.1288_+0000-cb6e341d9e339fcd61f519544ac89fe2dd5d3af5.crash.zip](https://github.com/DataDog/dd-sdk-ios/files/14402782/2024-02-14_14-32-50.1288_%2B0000-cb6e341d9e339fcd61f519544ac89fe2dd5d3af5.crash.zip)

**Comment by ivopintodasilva** [comment]
hi @maciejburda 👋 any news on this?

**Comment by ivopintodasilva** [comment]
@maciejburda any ETA for this fix to be rolled out?

**Comment by maciejburda** [comment]
Thank you for your message.

It's a high priority at this point. We'll let you know as soon as it's released.

**Comment by dmamie** [comment]
@maciejburda this issue is becoming critical for us and may even lead to us needing to switch away from datadog.

**Comment by maciejburda** [comment]
@ivopintodasilva 
I opened a PR with a fix proposal. We'll discuss with the team, and once we come to an agreement we will release a fix.

@dmamie 
Thank you for chiming in! For future bug reports / feature request I highly recommend using [official support channel](https://help.datadoghq.com/hc/en-us/requests/new). It's preferred option, as it provides you with a better visibility into the progress, as well as giving us a chance to request more details on the matter using private channels.

**Comment by maciejburda** [comment]
Hello @ivopintodasilva and @dmamie,

After extensive investigation and analysis with the team, we came to a few conclusions:
- Datadog SDK is not in the stack trace of crashed thread. Yes, we’re in the stack trace of some other threads, but this expected as SDK does heavy upload activities in app extensions.
- Neither Datadog SDK, or our dependency should cause `0xdead10cc` because the way we write to files does not create file locks. Please take a look at [our implementation](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogCore/Sources/Core/Storage/Files/File.swift) and [PLCrashReporter](https://github.com/microsoft/plcrashreporter/blob/6752f71de206f6a53fa6a758c3660fd9a7fe7527/Source/PLCrashAsync.c#L407).

We've found quite a few threads ([#1](https://inessential.com/2020/02/13/how_we_fixed_the_dreaded_0xdead10cc_cras.html), [#2](https://stackoverflow.com/questions/76213225/swift-runningboard-0xdead10cc-error-during-realm-database-writes-when-app-is-i), [#3](https://forums.developer.apple.com/forums/thread/728957)) mentioning `0xdead10cc` and different ways of dealing with it. From what we read SDK does not touch any APIs that might trigger it.

Although, since we have `backgroundTasksEnabled` configuration that is not fully functional within iOS extensions we decided to add this functionality. You can track the progress here https://github.com/DataDog/dd-sdk-ios/pull/1803.

This change is likely to indirectly decrease the amount of crashes due to extended lifetime of the extensions when it's enabled.

There might be still some things that we don't fully understand. It would be great to perform an experiment where you temporarily disable the Datadog SDK in the extensions and see if these crashes still appear. I'll close the issue for now, but feel free to open another one when you have more data after trying out the `backgroundTasksEnabled` and testing extensions without SDK enabled.
