### ISSUE TITLE
Unable to use swift-api-digester when Datadog is a dependency

### ISSUE THREAD

**Issue by aim2120** [DataDog/dd-sdk-ios#1717]
### Describe the bug

Hello!

I have Datadog as a dependency of my library (integrated with SPM). I'd like to use swift-api-digester to diagnose breaking API changes. Since I'm building for iOS, I do this by running `xcodebuild` and then `swift api-digester`. For my example module `TestModule`, these would be the commands I run:

```sh
xcodebuild -derivedDataPath .build -sdk "`xcrun --sdk iphonesimulator --show-sdk-path`" -scheme "TestModule" -target "arm64-apple-ios17.2-simulator" -destination "platform=iOS Simulator"

swift api-digester -dump-sdk -module TestModule -o testmodule.json -I .build/Build/Products/Debug-iphonesimulator -sdk "`xcrun --sdk iphonesimulator --show-sdk-path`" -target "arm64-apple-ios17.2-simulator"
```

The `xcodebuild` command succeeds; however, the swift-api-digester fails with this error:

```sh
<unknown>:0: error: missing required module 'DatadogPrivate'
Failed to load module: TestModule
```

Do you have any recommendations for how I might be able to circumvent this issue? FYI, I've already tried adding `OTHER_SWIFT_FLAGS="-Xcc -fmodule-map-file=\"\$(GENERATED_MODULEMAP_DIR)/DatadogPrivate.modulemap\"` to the `xcodebuild` command (based on the suggestion from [this issue](https://github.com/DataDog/dd-sdk-ios/issues/1085)), but that didn't help.

### Reproduction steps

Run the commands listed above with this example SPM library:

[TestModule.zip](https://github.com/DataDog/dd-sdk-ios/files/14552294/TestModule.zip)

### SDK logs

This is the build log of the `xcodebuild` command:
[build.log](https://github.com/DataDog/dd-sdk-ios/files/14552292/build.log)

This is the output of the `swift api-digester` command:
```sh
<unknown>:0: error: missing required module 'DatadogPrivate'
Failed to load module: TestModule
```

### Expected behavior

When I have Datadog as an SPM dependency, I can use swift-api-digester on my library successfully.

### Affected SDK versions

1.x and 2.x

### Latest working SDK version

None

### Did you confirm if the latest SDK version fixes the bug?

Yes (it doesn't)

### Integration Methods

SPM

### Xcode Version

15.2

### Swift Version

5.9

### MacOS Version

13.6.4

### Deployment Target

iOS 15+ (Simulator)

**Comment by maxep** [comment]
Hi @aim2120 👋 

Thanks for the sample project, it's very helpful. I think the root cause of your issue is described [here](https://forums.swift.org/t/issue-with-third-party-dependencies-inside-a-xcframework-through-swiftpm/41977/3).
> The general issue here is that the Swift compiler needs to be able to see all the modules being used at build-time, either via .swiftmodule/.swiftinterface or module maps.

The `DatadogPrivate.swiftmodule` is not generated at build because it's not exposed (private dependency of `DatadogCore`). As mentioned in the thread, you could use `@_implementationOnly import DatadogCore` to workaround this. Note that this will prevent exposing any `DatadogCore` swiftinterface from your module public interface.

Would that work for you?

**Comment by maxep** [comment]
Hey 👋 

I can only advise to upgrade to `2.x`, you can follow the [Migration Guide](https://github.com/DataDog/dd-sdk-ios/blob/develop/MIGRATION.md).

The `1.x` version did not support [Swift Module Stability](https://www.swift.org/blog/library-evolution/) because of name conflict between module and class, which might prevent from using `@_implementationOnly` (not sure..) but I don't see other workaround :/

**Comment by aim2120** [comment]
For sure, that makes the most sense (we should be using the latest anyway, but just haven't taken the time to migrate). Again, thanks for all the help! Glad to have a path forward 😎
