### ISSUE TITLE
"Connect RUM and Traces" - documentation outdated? 

### ISSUE THREAD

**Issue by alrocha** [DataDog/dd-sdk-ios#1758]
### Question

Hey peeps! 👋 

I was going throughout the documentation and seems like this file https://docs.datadoghq.com/real_user_monitoring/platform/connect_rum_and_traces/?tab=iosrum#opentelemetry-support is not updated with the latest version of the SDK since `firstPartyHostsTracing` doesn't exist anymore in the configuration init params, could you please have a look if is outdated? 

Thanks!

**Comment by ncreated** [comment]
Hey @alrocha 👋. Thanks for bringing this up. Indeed, there was a problem with this doc, I made a PR to fix it: 
- https://github.com/DataDog/documentation/pull/22476

The `firstPartyHostsTracing` parameter is however correct. You can find it both in [Trace](https://github.com/DataDog/dd-sdk-ios/blob/5334eab9cb5f9de2f47f62d9a951b3b05230938e/DatadogTrace/Sources/TraceConfiguration.swift#L97) and [RUM configuration](https://github.com/DataDog/dd-sdk-ios/blob/5334eab9cb5f9de2f47f62d9a951b3b05230938e/DatadogRUM/Sources/RUMConfiguration.swift#L230). The change I made was about using `RUM.enable()` instead of `Trace.enable()`. Ultimately, to configure distributed tracing in RUM, you should use:
```swift
RUM.enable(
    with: RUM.Configuration(
        applicationID: "<rum application id>",
        urlSessionTracking: .init(
            firstPartyHostsTracing: .trace(
                hosts: [
                    "example.com",
                    "api.yourdomain.com"
                ],
                sampleRate: 100
            )
        )
    )
)
```
or `.traceWithHeaders(hostsWithHeaders:sampleRate:)` if you need OTel headers.

Let me know if this is clear enough or if you have any other question on this topic.

**Comment by ncreated** [comment]
The documentation is now up to date. Closing 🙂.
