### ISSUE TITLE
Datadog RUM - swizzle() - main thread UI responsiveness issue

### ISSUE THREAD

**Issue by asetiyadi-MLB** [DataDog/dd-sdk-ios#1766]
### Describe the bug

During RUM initialization: `RUM.enable(with: RUM.Configuration)`, it invokes `uiApplicationSwizzler?.swizzle()`. This call generates a warning as shown in Xcode below. Wondering if this will create a potential compile error or performance issue once Swift 6 is released.

<img width="843" alt="Screenshot 2024-04-07 at 12 11 48 PM" src="https://github.com/DataDog/dd-sdk-ios/assets/145615544/9971e219-a8d5-465e-afbf-260271dcdc38">

### Reproduction steps

• Currently tested in SDK 2.7.1
• Make sure to enable RUM feature and invoke `RUM.enable` API

### Expected behavior

No main thread warnings should be generated

### Affected SDK versions

2.7.1

### Latest working SDK version

Not sure

### Did you confirm if the latest SDK version fixes the bug?

No

### Integration Methods

SPM

### Xcode Version

15.3

### Swift Version

5.9

### MacOS Version

Sonoma 14.3.1

### Deployment Target

iOS 16

**Comment by maxep** [comment]
Hi @asetiyadi-MLB 👋 

This code path is invoked when a user touches the screen and the warning appears to be from the `previousImplementation`. The `previousImplementation` is calling the implementation of `UIApplication.sendEvent`, so I suspect that something is blocking the main thread there. 

Do you override the `UIApplication.sendEvent` yourself? if not, do you use any other third-party library that could be swizzling the `UIApplication.sendEvent` method?

Do you have by any chance a sample project that reproduces the issue? it could be helpful to validate that the problem is coming from the Datadog SDK.

Thanks for your help!

**Comment by asetiyadi-MLB** [comment]
@maxep We did not override `UIApplication.sendEvent` and does not look like any other third party library use it from the global search as shown below.

<img width="565" alt="Screenshot 2024-04-08 at 4 15 26 PM" src="https://github.com/DataDog/dd-sdk-ios/assets/145615544/7beabda7-a089-45b6-b08d-0a1211fcf824">

**Comment by maxep** [comment]
Hi @asetiyadi-MLB 👋 

I'm enable to reproduce the runtime warning, I have tested with multiple sample projects. Do you have one that reproduces this that you could share with?

Thank you for your help on this!

**Comment by asetiyadi-MLB** [comment]
@maxep Sorry for the delay in responding. 
I have also tried to create a new sample project and use `2.7.1` and not able to reproduce the issue. Certainly is still happening on my main project. Based on your observation, what are the possible causes for this that I can pursue and dig deeper into?

FYI .. we use others third party SPMs like Firebase and OneSignal. I did check your initial suggestion if any other third party is using `UIApplication.sendEvent` and none other than Datadog.
