### ISSUE TITLE
Image render in session replay

### ISSUE THREAD

**Issue by jeremymarabel** [DataDog/dd-sdk-ios#1796]
### Question

Hi,

I'm currently in the process of binding this sdk to be able to use it in MAUI.
I managed to make almost everything work, but I can't get images and font icons to render into the session replays.

Images render like this : 
![image](https://github.com/DataDog/dd-sdk-ios/assets/15158008/cd1113c0-7236-47c3-a265-2165f42e3fc0)

And font icons like this : 
![image](https://github.com/DataDog/dd-sdk-ios/assets/15158008/1086587b-95ad-46ad-a77f-f63d965313b6)

I understand the feature is still in beta, just wanted to know if this is an issue purely on my side, or if this is something expected.

If this should work, I'd like to ask how are the images interpreted by the sdk ? (as MAUI use native control for images, maybe i just need to fill a specific field in the renderer for this to work ?)

Thanks !

**Comment by maciejburda** [comment]
Thank you for your insightful questions, @jeremymarabel.

Currently, Mobile Session Replay exclusively supports contextual images, such as system icons and embedded app images. Recording content images is on our roadmap and will be available soon. We intend to maintain contextual image recording as the default behaviour while adding additional properties to the Session Replay configuration object.

Regarding font support, it poses a complex issue due to copyright concerns. This feature is a lower priority currently, but your feedback is valuable. If you'd like to prioritise font support, please submit a feature request [here](https://help.datadoghq.com/hc/en-us/requests/new) to help us focus on this area.
