### ISSUE TITLE
 Issue with Manual Code Signing in Xcode

### ISSUE THREAD

**Issue by joylin66** [DataDog/dd-sdk-ios#1862]
### Question

Hello ,

I'm currently using this package via Swift Package Manager (SPM) in my Xcode project. When I have code signing set to automatic, everything works fine. However, when I switch to manual code signing, I encounter errors. It's worth noting that manual code signing works fine when I'm not using your package.

Could you please provide guidance on any additional configurations needed to ensure compatibility with manual code signing?

Thank you for your assistance.

**Comment by ganeshnj** [comment]
Hi @joylin66, thanks for reaching out.

Could you share what errors are you encountering? If you could share a sample app with reproducible steps will be helpful to get to the bottom of the issue.

**Comment by joylin66** [comment]
hi  Thank you for your response.
In my app packaging process,
 I'm utilizing Fastlane's build_app action to set the bundle ID and manage manual code signing

```
lane :pack_app do
    xcargsTxt = "PRODUCT_BUNDLE_IDENTIFIER='my.bundle.identifier' PROVISIONING_PROFILE_SPECIFIER='match AdHoc my.bundle.identifier' CODE_SIGN_IDENTITY='iPhone Distribution'"
    sync_code_signing(app_identifier: ["my.bundle.identifier"],readonly: true)
    build_app(
      scheme: "DataDogProject",
      export_method: "ad-hoc",
      xcargs: xcargsTxt,
      output_name: "datadogjoyTest.ipa",
      )
  end
```
Thank you for your assistance.

![dataDogError](https://github.com/DataDog/dd-sdk-ios/assets/59361254/253b6fed-08c6-4d73-8225-d124e7944950)

**Comment by ncreated** [comment]
@joylin66 This issue doesn't seem related to `dd-sdk-ios` - our package doesn't enforce any signing configuration. Please seek for help in Fastlane community, as it is likely related to Fastlane configuration. Otherwise, please provide vanilla configuration using just `xcodebuild`, where we can reproduce the problem.

PS. Maybe what you're missing is [`update_project_team`](https://docs.fastlane.tools/actions/update_project_team/) lane?

For now I will close this issue. Feel free to report a new one that uses vanilla configuration (`xcodebuild`).
