### ISSUE TITLE
Xamarin forms/Maui bindings

### ISSUE THREAD

**Issue by randomroxks** [DataDog/dd-sdk-ios#1868]
### Question

Hello:
 Is there a way to generate the xcframework so that i can create a XF/Maui bindings? I tried building the iOS SDK but keep on running into errors:
```
<unknown>:0: error: unable to set working directory: /var/folders/tg/72zl10b10ks2z1gw2c3vmnqm0000gn/T/com.datadoghq.api-surface-F9B55FF0-20FD-4882-95D4-80D3B3AFB5BF
/Users/anuragshukla/Library/Developer/Xcode/DerivedData/com.datadoghq-bcndgibpltrhgvfwpyshjyfhlhzy/Build/Intermediates.noindex/GeneratedModuleMaps-iphonesimulator/DatadogPrivate.modulemap:2:10: warning: umbrella directory '/var/folders/tg/72zl10b10ks2z1gw2c3vmnqm0000gn/T/com.datadoghq.api-surface-F9B55FF0-20FD-4882-95D4-80D3B3AFB5BF/DatadogCore/Private/include' not found
umbrella "/var/folders/tg/72zl10b10ks2z1gw2c3vmnqm0000gn/T/com.datadoghq.api-surface-F9B55FF0-20FD-4882-95D4-80D3B3AFB5BF/DatadogCore/Private/include"
```

thanks.

**Comment by ncreated** [comment]
Hey @randomroxks 👋. Unfortunately, we don't support Maui (see https://github.com/DataDog/dd-sdk-ios/issues/1617), hence we can't look into this problem.

To give you anything useful tho, the `DatadogPrivate.modulemap` mentioned in the error message [was removed](https://github.com/DataDog/dd-sdk-ios/pull/1746) in [2.9.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.9.0) version of the SDK. You may want to try the previous or next version (the latest is always recommended). If you are on the latest version already, then cleaning derived data might help (this file should not exist).

Because we won't be looking deeper into this, I will close this issue. Feel free to ask more questions related to the SDK itself - on this we can help 🙂!

**Comment by randomroxks** [comment]
I'm wondering if I can create a fat library? I can create binding from the fat library and AAR for Android.
