### ISSUE TITLE
Connecting custom Traces with RUM data using Graphql

### ISSUE THREAD

**Issue by soucolline** [DataDog/dd-sdk-ios#2115]
### Question

Hello,

I'm in the process of integrating Datadog into my app (using graphql).
Following the doc I've started with the automatic instrumentation on `URLSession` using `URLSessionInstrumentation.enable(with: .init(delegateClass: Apollo.URLSessionClient.self))` which works perfectly fine. I'm now getting all calls logged and opening them show me all the spans from my call to the backend and SQL queries, so far so good. 

As there are many calls being made in the app, I only want to log those who end up in errors so I first started to explore the `resourceAttributesProvider` callback on `RUM.Configuration`. Unfortunately the way graphql works is that every calls end up in a 200 even though they are errors and you have to parse the response to check for the errors property of the resulting JSON.
So using the property error of `resourceAttributesProvider` doesn't work as it's always nil.

I then thought about not using the automatic instrumentation and create the Trace by myself in the graphql Interceptor I already have. As it's specifically made for Graphql I have all the informations in it that I need to construct the error (I'm already doing that with the Sentry integration i have). 

So on the interceptor I do the following : 
```
func interceptAsync<Operation>(
        chain: RequestChain,
        request: HTTPRequest<Operation>,
        response: HTTPResponse<Operation>?,
        completion: @escaping (Result<GraphQLResult<Operation.Data>, Error>) -> Void
    ) where Operation: GraphQLOperation {
        
        if let errors = response?.parsedResponse?.errors {
            errors.forEach { error in
                let apiError = WPAPIError(gqlError: error)
                let operationType = Operation.operationType

                let trace = Tracer.shared().startSpan(operationName: Operation.operationName)
               
                trace.setError(kind: "api", message: error.message ?? "")
                trace.setTag(key: "http.status_code", value: apiError.code)
                trace.setTag(key: "http.method", value: "POST")
                trace.setTag(key: "json.response", value: String(response?.rawData.prettyPrintedJSONString ?? ""))
                
                trace.finish()
        }

        chain.proceedAsync(
            request: request,
            response: response,
            interceptor: self,
            completion: completion
        )
    }
```

I do get the Trace logged in DD with all the informations I provided but now I only have 1 span and don't see what's happening on the Backend side as I used to have with automatic instrumentation. 

Following some opened issues I saw here I added an interceptor at the request level to add the dd headers : 
```
func interceptAsync<Operation: GraphQLOperation>(
        chain: RequestChain,
        request: HTTPRequest<Operation>,
        response: HTTPResponse<Operation>?,
        completion: @escaping (Result<GraphQLResult<Operation.Data>, Error>) -> Void
    ) {
        let trace = Tracer.shared().startSpan(operationName: Operation.operationName)
        let headersWriter = HTTPHeadersWriter.init(sampleRate: 100)
       Tracer.shared().inject(spanContext: trace.context, writer: headersWriter)
        
          for (headerField, value) in headersWriter.traceHeaderFields {
              request.addHeader(name: headerField, value: value)
          }

        chain.proceedAsync(
            request: request,
            response: response,
            interceptor: self,
            completion: completion
        )
    }
```

I do see the X-datadog headers set properly (the same as for automatic instrumentation) but still only 1 span on the Trace.
I feel like there is something wrong with my setup but I can't pinpoint exactly what, do you see anything that I could have missed ?

Hope everything is clear and detailed, thanks a lot for your help

**Comment by maxep** [comment]
Hello @soucolline 👋  Thank you for he detailed report.

Do you use RUM and want to see the distributed trace of your RUM resource? Because the `resourceAttributesProvider` is for RUM resources while the `Tracer` is to collect spans in APM only (No RUM resource).

I will assume that you intend to use RUM Resource with distributed trace. There is 2 problems that can be resolved independently:

### 1. GraphQL Errors
Not every call endup with 200 status code in gql, more details [here](https://www.apollographql.com/docs/apollo-server/data/errors#setting-http-status-code-and-headers). 

But it's true that some error (such as operation resolution) can still have status code 200, that's because gql can return partial results. You can still report gql operation errors by using the `resourceAttributesProvider` closure and reporting the error as an attribute. e.g.:
```swift
resourceAttributesProvider: { _, _, data, _ in
    if let error = parse(error: data) {
        return ["error": error]
    }

    return nil
}
```

### 2. Report Resources with errors only
To filter resources with errors, you can use the `resouceEventMapper` from the RUM configuration. Returning `nil` in the event mapper will drop the resource event.

```swift
resourceEventMapper: { event in
    if let code = event.resource.statusCode, code > 400 {
        return event
    }

    if event.context?.contextInfo["error"] != nil {
        return event
    }

    return nil
}
```

I hope this helps!

**Comment by soucolline** [comment]
Hello @maxep, thanks for the detailed answer, I'm sorry the terminology is still a bit confusing for me between APM, RUM, Trace, Spans, I might be mixing things 🫣

I see what you mean for your solution, I'll try it out and get back to you if it's all good 

Do you know if I can have some control over the event to manually change the status code that's going to be displayed on DD ? 
![Image](https://github.com/user-attachments/assets/741159eb-9121-450d-bd80-15c4bbce6eb6)
To avoid showing 200 while the "graphql error" is a 401 for example

**Comment by maxep** [comment]
Hey @soucolline !

No problem, it can be confusing indeed, we support multiple products with our SDK and products can have correlation.
- `DatadogTrace` module allows you to collect spans for APM (Application Performance Monitoring) and visualise traces. This include Distributed Traces which are distributed between your clients and across your infrastructure.
- `DatadogRUM` collects session information for RUM (Real User Monitoring) product. It includes network request information through Session Resources. A Resource event can also generate a Distributed Trace in APM to give you full visibility.

> Do you know if I can have some control over the event to manually change the status code that's going to be displayed on DD ? ![Image](https://github.com/user-attachments/assets/741159eb-9121-450d-bd80-15c4bbce6eb6) 
To avoid showing 200 while the "graphql error" is a 401 for example

Our instrumentation strictly follow the HTTP status, so if your server returns a `401` status you will see it in DD.
I would recommend to keep status code align with what the server returns, otherwise it might get confusing and difficult to troubleshoot. If you have control over your gql server, you can look at changing the status code depending on the error thrown, [this documentation](https://www.apollographql.com/docs/apollo-server/data/errors#setting-http-status-code-and-headers) will give you more information.
