### ISSUE TITLE
Is verbosityLevel working?

### ISSUE THREAD

**Issue by akun1** [DataDog/dd-sdk-ios#212]
### The thing

Any value we set `Datadog.verbosityLevel` to has no effect on the logs we print out to console using `printLogsToConsole(true)` and on the logs we send to Datadog using `.sendLogsToDatadog(true)`

Tell us the thing 🙂

Datadog is working well and sending logs like we want! We can even print them to the console. However, when we try to change verbosity via that variable, it does not seem to affect anything (ie all levels of logs are still being sent).

Any help would be appreciated!

**Comment by ncreated** [comment]
Hello @akun1 👋, thanks for using Datadog 🙂! The short answer is: yes it works. However, its invented usage is not the one you describe. `Datadog.verbosityLevel` **is not a logs threshold**. It is a debug utility to help you discover any problems with using our SDK.

```swift
/// Verbosity level of Datadog SDK. Can be used for debugging purposes.
/// If set, internal events occuring inside SDK will be printed to debugger console if their level is equal or greater than `verbosityLevel`.
/// Default is `nil`.
public static var verbosityLevel: LogLevel? = nil
```

The SDK does many things internally (from writing logs to file, to sanitizing log attributes to uploading them to server). Any of this operations may fail due to external circumstances or a bad configuration. To help users discover issues, we provide the `.verbosityLevel` setting which makes the SDK "verbose". Once enabled, it will start printing significant events from the SDK's internal operations, like [this](https://github.com/DataDog/dd-sdk-ios/blob/a240fc23b3c90437deb836a3bda7b4e8a3004d9b/Sources/Datadog/Core/Upload/DataUploadWorker.swift#L60), [this](https://github.com/DataDog/dd-sdk-ios/blob/a240fc23b3c90437deb836a3bda7b4e8a3004d9b/Sources/Datadog/Logging/Log/LogSanitizer.swift#L92), or even [that](https://github.com/DataDog/dd-sdk-ios/blob/a240fc23b3c90437deb836a3bda7b4e8a3004d9b/Sources/Datadog/Core/Persistence/FileWriter.swift#L48). It should be used as the first-resort to investigate "my logs are not uploaded" problems, and you may want to keep it `nil` in production builds (no verbosity). Those logs are only printed to the console and never send to Datadog.

What you describe is logs filtering above the given severity level. This can be done at multiple levels of the infrastructure: you could filter logs on your end before passing them to the SDK, we could filter them in the SDK (no such feature right now) and last, what we recommend, **you can filter them on the [app.datadoghq.com](https://app.datadoghq.com/) processing level**. As we advocate [Logging without Limits™](https://www.datadoghq.com/blog/logging-without-limits/), we provide efficient tooling to ingest terabytes of log data every day, and filter it later using our [Log Processing Pipelines](https://app.datadoghq.com/logs/pipelines). We digest everything and you decide on the interesting data and configure its retention. And we do not charge for digesting 🙂.

Hope this answers the question... let me know!

**Comment by akun1** [comment]
Great! Thank you for such a comprehensive explanation! 😁
