### ISSUE TITLE
Spike in NSURLErrorDomain -1005 errors

### ISSUE THREAD

**Issue by PSinha1202** [DataDog/dd-sdk-ios#2159]
### Question

Hi Team, 

We have recently upgraded our DataDog iOS sdk to 2.20.0 and from the very next day we are seeing huge spike on the error 
NSURLErrorDomain - -1005: The network connection was lost.

We understand sometime users can have no network and trying to access the app can get these errors. But to our surprise the error rate has increased by 38.0k errors in a day. 

Secondly there is not errors seen before the sdk update. We are trying to understand how none of the users can have no network issue anytime before. 

That definitely seems unusual. Would like to know more about the mechanism behind these errors reporting and if there is any way we can handle that from our side.

**Comment by mariedm** [comment]
Hi @PSinha1202, 
Which SDK version were you using before upgrading to v2.20?
Could you also share the details of your environment, please? Thanks!

**Comment by mariedm** [comment]
In the meantime, you can filter out network errors. There is a `network` error facet on the left.

![Image](https://github.com/user-attachments/assets/0214ef58-25ff-482f-a769-e14eb42d9442)

You can also drop these errors using the even mapper API:
```
rumConfig.errorEventMapper = { event in
    return event.error.source != .network ? nil : event // drop NETWORK errors
}
```

**Comment by mariedm** [comment]
Hi again,

It turns out that the Error Tracking team started fingerprinting console and network RUM errors on December 11, which explains the spike you're seeing.

If you’d like to filter these errors out, you can add `-@error.source:network` to your query in Error Tracking.

Let us know if you have any more questions!<img width="1342" alt="Image" src="https://github.com/user-attachments/assets/bb506ec0-192d-41d5-aba8-3ee22e98e575" />

**Comment by PSinha1202** [comment]
Thanks for the response, appreciated. 

So my follow up questions is: 

is those errors are actual errors, (user facing network issues) or something sdk team has added to get some data out of it on some specific event?

The reason of the question is, we can surely filter them out if users are not seeing any issues on app but say if there are some heavy network drop, we would like to know the reason why suddenly there is a drop coming in and if users are affected. Would love to know your guidance to handle this.

**Comment by PSinha1202** [comment]
> Which SDK version were you using before upgrading to v2.20

We have moved from 1.11.1 -- 2.20.0, so it was a major jump

> Could you also share the details of your environment
The error reported is on prod, not sure if you want more details, if so please feel free to let us know.

**Comment by ncreated** [comment]
Hi @PSinha1202, thank you for your detailed follow-up. Let me clarify the situation briefly:

#### Source of Confusion
The spike is not due to any changes in the Datadog iOS SDK itself but a new feature deployed to Error Tracking on December 11th, as noted by @mariedm. These errors were always tracked in RUM but were not surfaced in Error Tracking until this update.

#### Understanding and Handling the `NSURLErrorDomain` `-1005` Errors
The `NSURLErrorDomain` error code `-1005` ("The network connection was lost") is a real, user-facing issue. This error originates from your app and reflects failed networking requests.

Apple offers guidance on this error, see [Handling “The network connection was lost” Errors](https://developer.apple.com/library/archive/qa/qa1941/_index.html#//apple_ref/doc/uid/DTS40017602):

> (...) it’s reasonable to expect a small number of NSURLErrorNetworkConnectionLost errors caused by problems with the underlying network. However, if you’re seeing a large number of these errors, and especially if they are raised in environments with good network connectivity, there might be a problem with NSURLSession talking to your server. You can investigate that by looking at the on-the-wire traffic to see whether there’s an obvious underlying cause for these errors, for example, your server actually closing connections unexpectedly

To analyze these errors in Datadog, you can check error.connectivity.* attributes for these errors. Errors linked to poor connectivity are expected, but if they occur under good conditions, they may indicate issues with URLSession or your server.

There’s no universal approach to handling these errors. Whether they can be ignored or require action depends on your app's context. Our SDK tracks them to provide visibility, so you can make an informed decision. If you decide to filter or mute them, refer to earlier advice from @mariedm.

---

Since this resolves the concern and confirms no SDK issue, I’ll close this GitHub Issue. The title has also been updated to reflect this. If you have further questions, feel free to ask below—we’re happy to assist!

**Comment by PSinha1202** [comment]
@ncreated Thanks for the info, but i checked and don't see any connectivity for the error type. I saw them as a separate parameter but not the conditions. 

<img width="437" alt="Image" src="https://github.com/user-attachments/assets/45bcd3a4-78be-4d4c-963d-7d8f1b906ee0" />

**Comment by ncreated** [comment]
Hey @PSinha1202 👋. My apologies—I should have referred to `connectivity:*`, not `error.connectivity:*`. Our SDK surfaces the connectivity details provided by iOS (such as cellular technology, enabled interfaces, and overall connection status). You can find more information in our [iOS Data Collected > Connectivity](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/ios/data_collected#connectivity) docs. If you need additional connectivity data, feel free to submit a feature request through our [Support channel](https://www.datadoghq.com/support/).

It may also help to cross-check your server logs to ensure connections aren’t being closed unexpectedly. If you find these errors to be false positives—Apple notes a small number of NSURLErrorNetworkConnectionLost errors is normal—you can mute them using the event mapper API mentioned earlier.

Ultimately, how you handle these errors depends on your app’s specific needs, and based on what we see, this behavior isn’t related to any issue with the Datadog iOS SDK. For further guidance or in-depth troubleshooting, please reach out to our [Support channel](https://www.datadoghq.com/support/). Thank you!
