### ISSUE TITLE
Is there an option to capture NSLog emitted from other frameworks?

### ISSUE THREAD

**Issue by hyling** [DataDog/dd-sdk-ios#227]
Is there an option to capture NSLogs emitted from frameworks I'm using?  Something similar to redirecting std error to a file but to Datadog instead?  https://stackoverflow.com/questions/7271528/how-to-nslog-into-a-file

**Comment by ncreated** [comment]
Hello @hyling 👋 🙂. The short answer is: no, we do not provide integrations with the system logging utilities ([NSLog](https://developer.apple.com/documentation/foundation/1395275-nslog), [print](https://developer.apple.com/documentation/swift/1541053-print), [os_log](https://developer.apple.com/documentation/os/os_log), [Logger](https://developer.apple.com/documentation/os/logger)). We haven't yet consider it and it's not on our roadmap at this moment - in my understanding, those are utilities to use in `DEBUG` configuration, while our `Logger` is made for loggin in production apps, so this integration may be not trivial when considering all environments.

You may need to capture the frameworks output on your side and send it using our `Logger`. If necessary, make sure the framework logs are available in `RELEASE` configuration (this may depend on the vendor), so you can collect this data from the app in production.

**Comment by hyling** [comment]
Hi @ncreated 👋🏼.  

By:
> those are utilities to use in DEBUG configuration
Are you referring to NSLog,  print, os_log, Logger?

**Comment by ncreated** [comment]
@hyling Yes, what I mean is that all Apple logging APIs are different and have different features and optimisations, e.g.:
* `print()`, `NSLog()` - do not support severity levels (info / error / ...),
* `os_log` - has a low-performance overhead and archives the logs on the device (cheap) for later retrieval (expensive),
* [`Logger`](https://developer.apple.com/documentation/os/logger) - new API introduced in iOS14, supports logs redaction, log severity levels and AFAIK the same performance optimisations as `os_log`,
* [`swift-log`](https://github.com/apple/swift-log) - this is the closest one to Datadog Logger, it supports Logger metadata attributes and similar severity levels as we do.

Hence, using `print()` or `NSLog()` is handy when debugging, but won't be as powerful as using our `Datadog.Logger` in production apps (due to no severity and no attributes support). Also, please note that `Datadog.Logger` has this feature:
```swift
logger = Logger.builder
   .printLogsToConsole(true, usingFormat: .shortWith(prefix: "[iOS App] "))
```
which will print all your logs to the console, so you can replace all `print()` calls with `Datadog.Logger` and you will not lost anything, but win severity + attributes. If you want to disable logs upload in `DEBUG` builds, you can also set:
```swift
#if DEBUG
.sendLogsToDatadog(false)
#endif
```
With those two flags, you'll have more than `print()` or `NSLog()` by only using `Datadog.Logger`.

Again, we don't have any defined plans to add support for Apple logging APIs, which doesn't mean we won't add it one day 🙂.

**Comment by ncreated** [comment]
Hey @hyling 👋. Does my answer give you enough context on the topic 🙂? We'd love to follow up on this issue / close it if possible.

**Comment by hyling** [comment]
Hi @ncreated thanks for the reminder!  I apologize for the delay I had formulated a response but then got pulled away to work on an urgent bugfix.

After reading your response I just want to clarify this.  It sounds like you thought I wanted to keep using Apple's logging APIs then have Datalog capture that output but that's not not what I want to do.  I've already replaced the logging in my app with Datadog APIs but for the 3rd party frameworks which I have no control over I'd still like to capture their logs because it's valuable for debugging purposes.  The logging from these frameworks are controlled by a flag so they would still be accessible in a release configuration.

The most value Datadog logging provides me is helping me fix hard to reproduce bugs by capturing logs from devices running in production environments.  The ability to capture logs from the 3rd party frameworks that my apps depends on further expands on that valuable capability.

**Comment by ncreated** [comment]
Thanks for the update @hyling! Yes, I get your use case well. Anyway, as we don't have plans for it right now, you could either try capturing those logs on your side (and sending it to Datadog) or asking for a better best strategy to handle errors and failures in 3rd party code. Just keep the privacy aspect in mind - some 3rd party SDKs may print sensitive information, which you probably don't want to collect.

Thanks for updating the issue, appreciate 👌.

**Comment by hyling** [comment]
No problem.  Thanks for the tips and the detailed responses.  They were informative and helpful!
