### ISSUE TITLE
clientToken security measures on open source

### ISSUE THREAD

**Issue by fdoxyz** [DataDog/dd-sdk-ios#311]
Hello everyone, we're interested in using DataDog's logging for our mobile apps as we're already using other DataDog services.

We tested out the integration and it's working well. We're curious about the security measures we have to take when using the client token. [The documentation](https://docs.datadoghq.com/logs/log_collection/ios) mentions the following:

> For security reasons, you must use a client token: you cannot use Datadog API keys to configure the dd-sdk-ios library as they would be exposed client-side in the iOS application IPA byte code.

From this I understand the client token is considered safe even if disclosed (as they will be exposed in the byte code). If we are working on an app that is open source, is it still safe to publicly commit the token in the source code? 

How is the client token verified under the hood to ensure only logs coming from the production release are coming through in our logs? In other words, what prevents someone from using our client token and eventually send logs into our service?

Is the SDK validating the Bundle Identifier on a signed app? I wasn't able to find any documentation to make sure something like this would prevent bad actors from spamming our logs.

Thanks!

**Comment by fdoxyz** [comment]
Just to further clarify: We can use something like [xcconfig files](https://nshipster.com/xcconfig/) to avoid committing the token itself into the publicly available code. This doesn't seem [bullet proof](https://nshipster.com/secrets/) though, so AKAICT the token may still be decoded/intercepted.

If the token is generally safe though we may just add the token to the source code directly to avoid the extra step. Just wanted to reach out to better understand the steps we have to take in order to avoid someone abuse our service.

**Comment by ncreated** [comment]
Hello @fdoxyz 👋. Thank you for looking at Datadog Logging 🙂!

The Client Token is granted for an app and **it can be easily revoked if compromised**. CT can be only used to send data to Datadog, but **not for reading it**, so your data is safe once delivered. The SDK doesn't incorporate any additional logic to match the app instance (bundle ID / signing certificate) with the CT.

Speaking about Datadog Logging - to mitigate the hypothetical impact of abuse (and spamming), you may want to look into [Log Index](https://docs.datadoghq.com/logs/indexes/) and [Processing Pipelines](https://docs.datadoghq.com/logs/processing/) to read more about daily quotas and sampling rules which can be installed there.

> We can use something like [xcconfig](https://nshipster.com/xcconfig/) files to avoid committing the token itself into the publicly available code. This doesn't seem [bullet proof](https://nshipster.com/secrets/) though, so AKAICT the token may still be decoded/intercepted.

Injecting the CT through `.xcconfig` sounds perfectly valid. Because at the end the CT is shipped to unsafe environments (as you say: it is exposed in the byte code), the application may decide on implementing additional obscurity mechanics to make its visibility less obvious, but keep in mind that our CT is write-only and your data cannot be compromised due to abuse.

Thank you again for reaching us and let me know if this answers your questions 🙂.

**Comment by fdoxyz** [comment]
Thank you for the thorough clarification @ncreated, it definitely answers my questions and we now have a better understanding of how the CT works.

Looking forward to the insights we may gather after implementing this. Great job to you and the team behind the project all around 👍

**Comment by ncreated** [comment]
Thank you @fdoxyz 🙂, happy to help 🚀 !
