### ISSUE TITLE
Send logs immediately in app extension?

### ISSUE THREAD

**Issue by lmramirez** [DataDog/dd-sdk-ios#52]
Hi, first off thanks to you all for creating this sdk. While it's not in our production app yet, it's working great for us in testing.

One thing I'm trying to figure out: We have a broadcast extension which has a short lifecycle. Is there a way to configure the datadog sdk to send logs immediately? Our extension can be killed at any time and I want to make sure all of our logs make it to datadog. I was poking through the code but it wasn't obvious if this was possible.

Thanks!

**Comment by ncreated** [comment]
Hello @lmramirez 👋 thanks for trying out the SDK 🙂. As for now, there's no public API to configure the data upload frequency. We rather avoid exposing it so that users do not end up with a configuration that is ineffective or kills the app performance. Instead, with "immediate write" and "deferred upload" strategy implemented by the SDK, apps should not care about enforcing immediate uploads. We do our best to make sure the logs are delivered in a performant way.

The upload frequency is dynamic - it might vary from `1s` to `20s` depending on the logging pressure. Logs are written to the file system and they should be uploaded in the next session if app was terminated or suspended.

I think that your use case of short-lived app extension falls somehow beyond our upload heuristic. Could you give us more insight into this extension lifecycle?
* How long does it run in average?
* How often do your users come back to the extension?

We are going investigate the use case of app extensions for the SDK, so I put the enhancement label on this issue. Stay tuned we'll try to address it.

**Comment by lmramirez** [comment]
@ncreated thank you for the detailed response.

The app allows users to make screen recordings of their iOS devices, so the time the extension runs ranges from about 15 seconds to maybe an hour in some cases. 
Some users come back frequently and make daily recordings and others do not return to the extension for weeks. Users come back to our host application more often than they come back to our extension, since the host application providers other functionality as well.

I haven't dug too deep into the datadog implementation,  but is there a way to configure the location logs are written to on disk? It would be nice to have the option to configure this to point at a location in our App Group directory, so that it could be read and uploaded by the host application maybe?

Again, thanks to you and the datadog team for working on this! We have some hard to debug issues in our app extension and this sdk is already helping us a lot in testing.

**Comment by ncreated** [comment]
Thanks for details 👌. So as I understand you manage to upload some logs from the extension, but some number of short & unfrequent sessions is lost. One thing to comment here is that some percent of logs will be lost even when we apply the fix - due to our internal constraints we don't process logs that are significantly old. But even with this, the enhancement should give you a viable benefit.

> I haven't dug too deep into the datadog implementation, but is there a way to configure the location logs are written to on disk?

We store data [in `Library/Caches` subdirectory](https://github.com/DataDog/dd-sdk-ios/blob/68fac654b6b2ec3fd64476f4b322f2effd632c8a/Sources/Datadog/Core/Persistence/Files/Directory.swift#L51), but this is internal thing to the SDK. Currently we don't think about making this configurable for the same reasons I explained above (this will introduce many edge cases and put huge load on the maintenance).

> It would be nice to have the option to configure this to point at a location in our App Group directory, so that it could be read and uploaded by the host application maybe?

Indeed, that might be one idea for the enhancement. However, AFAIK App Group configuration does not come out-of-the-box and must be opted-in, so may not cover other app extension use cases. We have some other ideas in mind and soon will give them a shot 🙂.

> Again, thanks to you and the datadog team for working on this! We have some hard to debug issues in our app extension and this sdk is already helping us a lot in testing.

Ah, thank you 🤗, I'm gonna share it with the team.

**Comment by lmramirez** [comment]
> Thanks for details 👌. So as I understand you manage to upload some logs from the extension, but some number of short & unfrequent sessions is lost

Yep, this is correct.

And totally understand about configurability. App group is opt-in, so devs would need to provide their app group identifier as part of setup if that was an option.

Thanks for your help!

**Comment by ncreated** [comment]
Hey @lmramirez 👋. We decided to implement a different write / upload performance preset for SDK running in app extension. Hope this will address your problem and result with significantly more logs delivered. It was just merged - please stay tuned for the next release and let us know this helps.

**Comment by lmramirez** [comment]
@ncreated thank you so much!! Will give that a try
