### ISSUE TITLE
crash reports not uploaded

### ISSUE THREAD

**Issue by jules15** [DataDog/dd-sdk-ios#740]
I'm using the DataDog `1.8.0` SDK (iOS) for crash reporting. I have integrated the SDK and am initializing it like so:

```
            #if DEBUG
            Datadog.verbosityLevel = .debug
            #endif
            
            Datadog.initialize(
                appContext: .init(),
                trackingConsent: .granted,
                configuration: Datadog.Configuration
                    .builderUsing(
                        rumApplicationID: appId,
                        clientToken: clientToken,
                        environment: environment
                    )
                    .enableLogging(false)
                    .enableTracing(false)
                    .enableCrashReporting(using: DDCrashReportingPlugin())
                    .build()
            )
            
            Global.rum = RUMMonitor.initialize()
```

I have implemented a self-crash feature in the app to test crash-reporting (I have tried both `fatalError(...)` and `[][1]`). I run the app on-device (not simulator) and invoke the crash. I then connect my device to Xcode and restart the app so that I can watch console logs. However, when I restart the app, all I see is the following in the console:

[DATADOG SDK] 🐶 → 09:36:50.210 [DEBUG] 💡 (rum) No upload. Batch to upload: NO, System conditions: ✅

Also, no crash reports have appeared in the DataDog RUM console. I have tried several things and the behavior is always the same.

I don't see any documentation describing possible restrictions on the crash-reporting functionality. Are there any? For example:

- Should crash reporting work on debug/non-optimized builds?
- Should crash reports work on apps installed from Xcode, or only on apps installed from the App Store or from Testflight?

**Comment by ncreated** [comment]
Hello @jules15 👋. Before `1.9.0`, events (including crashes) are only tracked in view context, which means there must be some view started so we can associate the error (crash) with. In your snippet that would mean either starting RUM view manually (`Global.rum.startView(...)`), or using our auto-instrumentation to track view controllers as RUM views:
```swift
.enableLogging(false)
.enableTracing(false)
.trackUIKitRUMViews() // <- this, assuming you use UIKit for presenting view controller
.enableCrashReporting(using: DDCrashReportingPlugin())
```
For testing, I'd also recommend using `Datadog.debugRUM = true` option (similar to `Datadog.verbosityLevel` setting that you use). It will display small overlay with the name of current RUM view at the bottom of app screen, indicating that you track views correctly.

The constraint on first view was significantly enhanced in our recent [`1.9.0`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.9.0), so I'd recommend upgrading to this version. Since `1.9.0`, all events that happen before presenting first view are considered "application launch" events and the SDK will create "ApplicationLaunch" view for collecting them. Also, `1.9.0` adds more debug logs so you should see more information about the crash report processing thanks to `Datadog.verbosityLevel = .debug` 👍.

Other than ensuring RUM view presence before crash (prior to `1.9.0`) there are no other constraints:
> Should crash reporting work on debug/non-optimized builds?

Yes 👍.

> Should crash reports work on apps installed from Xcode, or only on apps installed from the App Store or from Testflight?

Yes, it works in iOS Simulator and when running app from Xcode on device 👍. The only requirement here is that you need to crash the app while debugger is disconnected (otherwise Xcode will consume the crash, without passing it to our crash reporter).

**Comment by jules15** [comment]
Thanks. Updating to `1.9.0` seems to have fixed things. But I have a follow-up question: Is 1.9.0 still considered "beta", or is it now suitable for production apps?

**Comment by ncreated** [comment]
`1.9.0` is a regular release and you can use it in production 🙂. As long as our release is not marked as pre-release on GH or annotated with `-beta`, `-alpha` or `-rc` it is considered stable.

I'm happy it helped! I'm closing this issue, but feel free to ask more questions.
