### ISSUE TITLE
CrashReporter static only?

### ISSUE THREAD

**Issue by jostster** [DataDog/dd-sdk-ios#828]
### The thing

Is there a particular reason that DatadogCrashReporter is static only? We want to only roll this out to a small set of users right now so it doesn't make sense to bundle and load it for everyone, even if they are not in the rollout.

**Comment by maxep** [comment]
Hey @jostster,

The reason is that `DatadogCrashReporter` depends on [PLCrashReporter](https://github.com/microsoft/plcrashreporter) which includes statically linked binary.
Both `DatadogCrashReporter` and `PLCrashReporter` are lightweight with no resources, the impact on your application bundle size will be minimal. You can safely hide the configuration of `DatadogCrashReporter` behind a compilation flag.

I will close this issue, but feel free to post any other comment 👍
