### ISSUE TITLE
Can't use Datadog as a dependancy in custom SPM package due to Datadog UIKit dependancy

### ISSUE THREAD

**Issue by anhar** [DataDog/dd-sdk-ios#931]
### The issue

📝 Give us the error message you receive, describe the problem and answer the questions.

Here's an example project that reproduces the issue: [https://github.com/anhar/Datadog-as-a-dependency-bug](https://github.com/anhar/Datadog-as-a-dependency-bug)

The problem seems to stem from that SPM doesn't allow you to restrict what platforms a SPM package supports. Therefore when adding Datadog as a dependancy in a custom Swift Package it will fail with this error:

```
/Users/Username/Library/Developer/Xcode/DerivedData/naloggerkit-ios-glifxtnmcqyhuebipvwuibfeqtci/SourcePackages/checkouts/dd-sdk-ios/Sources/_Datadog_Private/ObjcAppLaunchHandler.m:9:9: UIKit is not available when building for macOS. Consider using `#if !TARGET_OS_OSX` to conditionally import this framework, first importing TargetConditionals.h if necessary.
```

---

#### Datadog SDK version:

_Which version of the Datadog SDK causes this problem? e.g. `1.2.0`_

1.11.1

#### Last working Datadog SDK version:

_What is the last Datadog SDK version where this problem didn't occur? e.g. `1.1.0`_

N/A

#### Dependency Manager:

_Which dependency manager do you use? e.g. Cocoapods / Carthage / SPM / ..._

SPM

#### Other toolset:

_Do you use additional tools with your dependency manager? e.g. [CarthageCache](https://github.com/Wolox/carthage_cache)_

No other additional tools were used.

#### Xcode version:

_e.g. `Xcode 11.5 (11E608c)`_

Xcode version 13.4.1 (13F100)

#### Swift version:

_e.g. `5.1`_

Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: arm64-apple-macosx12.0

#### Deployment Target:

_What is the Deployment Target of your app? e.g. `iOS 12`, `iPhone` + `iPad`_

SPM Package, ideally just iOS and iPadOS

#### macOS version:

_e.g. `macOS Catalina 10.15.5 (19F96)`_

MacOS version 12.4 (21F79)

**Comment by maxep** [comment]
Hi @anhar ! Thank you for the report.

Indeed, SPM does not provide a way of restricting supported platforms at the package level. The only option is to select an iOS target device:
![image](https://user-images.githubusercontent.com/6815992/179581102-eedd3f4d-4fe6-44ab-9c65-1c4548b0ab2a.png)

The Datadog SDK currently supports iOS and tvOS. If you plan on supporting more platforms with your package, you can add a condition to the Datadog dependency so it's only resolved on those 2 platforms, such as:

``` swift
.target(
    name: "FooLoggerKit",
    dependencies: [
        .product(
            name: "Datadog",
            package: "dd-sdk-ios",
            condition: .when(platforms: [.iOS, .tvOS])
        ),
    ]
),
```

I hope this helps! I'm closing this ticket since it's not an issue on our side, but feel free to add any comment to this thread.
