### ISSUE TITLE
Considering SSL pinning

### ISSUE THREAD

**Issue by nicolas-vivot** [DataDog/dd-sdk-ios#932]
### Adding SSL pinning to HTTPS communications

We are using your SDK within our iOS application to monitor our users, and we recently ran a security scan on DataTheorem of our application.
One security issue was found within your SDK, allowing potential man in the middle attacks due to non SSL pinning implementation when communicating with your server API through the http client.

### This ticket purpose

I know that for a monitoring platform / sdk, pinning with certificates will definitely increase the integration complexity, for both the clients (us) and the service provider (you).
Therefore, we should first discuss about this, balancing the pros and cons and see whether it's doable and how.

### Security report details

![datadog_ssl_pinning_1](https://user-images.githubusercontent.com/79290619/179656442-9b46689f-2d49-4232-82c7-44dfd930db2e.png)

![datadog_ssl_pinning_2](https://user-images.githubusercontent.com/79290619/179656452-878c7179-2c40-46aa-a48a-50571d11763b.png)

### Code location

The location in your code when changes should be made is [the http client class](https://github.com/DataDog/dd-sdk-ios/blob/develop/Sources/Datadog/Core/Upload/HTTPClient.swift#L31), when the url session is created.

### How to address it

Stackoverflow thread on how to address this:
https://stackoverflow.com/questions/34223291/ios-certificate-pinning-with-swift-and-nsurlsession

**Comment by xgouchet** [comment]
Hi @nicolas-vivot and thanks for raising this topic.

Certificate pinning is indeed a mechanism that would ensure that the data sent by Datadog (including PII that might be in it) could not be read by a MitM attack. The main issue here is indeed related to the integration.

Our intake servers use certificates with a 1 year lifespan, following the consensual security guidelines (among others, Apple will reject any certificate with a validity longer than 398 days on iOS, and Google has similar checks in place). Because of this fast rotation, certificate pinning would essentially block the SDK within a year, making our customers blind to events happening on their users' devices. We already know that upgrading to the latest version of the SDK takes some time for most of our customers, and it takes even longer for the end users to upgrade their applications. Having a non negligible portion of user sessions not being reported would essentially make our SDK useless. Besides our Certificate rotation process would not easily allow us to get the certificate in advance to be ready for future changes. Not to mention the problem of unscheduled certificates changes that could happen at a moment's notice.

Also even if some PII might be discovered using a MitM attack, the impact is relatively small, and the cost of maintaining certificate pinning will be too much for the relative benefit it might have.

That being said, our SDK is open source, so if certificate pinning is a hard requirement for you, you can of course fork it and add the certificate pinning mechanism in the class you mentioned.

**Comment by nicolas-vivot** [comment]
Hi @xgouchet 

Thank you for your fast reply, appreciate it.

Got it, let's close it then.
